### PR TITLE
Fix modes for LV600S Humidifier

### PR DESCRIPTION
**Pull request by igor-panteleev**

### CODE REVIEW

**Comment by vlebourl** [comment]
hey! thanks for the contribution!
does this fix #125?

**Comment by vlebourl** [comment]
Can you apply pre-commit hooks to reformat the code? 
Also can you merge latest main (just pushed it) to fix the hassfest validation?
Cheers

**Comment by vlebourl** [comment]
I don't own the LV600S, do you have a display switch? mine has this:
image
which is mapped to the display switch:
image

I've seen from an other user's LV600S that both Display and Night light switches exist. What do they relate to?

**Comment by vlebourl** [comment]
Just waiting on your answer on #125 and the switches in HA, then happy to merge.

**Comment by igor-panteleev** [comment]
> hey! thanks for the contribution! does this fix #125?

Sure, this PR was addressed to fix this issue. 



> Can you apply pre-commit hooks to reformat the code? Also can you merge latest main (just pushed it) to fix the hassfest validation? Cheers

Just did it. I think a "Contribution" section should be added to the readme file to make this process a bit more obvious.


> I've seen from an other user's LV600S that both Display and Night light switches exist. What do they relate to?

For LV600S there is a display switch and it works like it suppose to (turns the display on and off)
For "nightlight" pyvevync list it as a feature for LV600S in `VeSyncHumid200300S.features` but it seems to be doing nothing. I've been experimenting yesterday with `set_night_light_brightness`, but changing it seems to have no effect.

**Comment by vlebourl** [comment]
Thanks, I'll merge as is, leaving the nightlight button for now, if this is a fix on the side of pyvesync, I'll maybe open an issue there.

**Pull request merged**
